Customize the loading of cards on page #3
Terro216/Cinema-AI-Front pull request #5
Opened 2023-02-26 17:02 UTC by VasilyRazdorsky

Настроил загрузку 1 страницы топ 250 фильмов на экран

2023-02-26 17:08 UTC, VasilyRazdorsky commented
Над дизайном если что всё ещё думаю, это оказалось труднее чем я думал

2023-02-26 22:26 UTC, Terro216 commented on src/pages/Home.tsx
>      queryKey: ['top'],
здесь можно добавить тип топа
```js
queryKey: ['top', {type: 'TOP_250_BEST_FILMS'}],
```

2023-02-26 22:39 UTC, Terro216 commented on src/pages/Home.tsx
> +  const cards = query.data?.data.films;
зачем эта переменная?

2023-02-26 22:41 UTC, Terro216 commented on src/styles/card.scss
> +  flex-direction: column;
Почему не row?.... Человек же справа-налево смотрит

2023-02-26 22:46 UTC, Terro216 commented on src/styles/index.scss
> +@import 'card';
Можно вообще посмотреть в сторону модульных стилей
https://github.com/css-modules/css-modules
Переименовать card.scss в card.module.scss и импортировать в компоненте, что бы не возникало никаких проблем с пересечением стилей

2023-02-26 22:47 UTC, Terro216 commented on src/styles/card.scss
> +  &__info {
А как ты написал стили под нигде не используемый класс? Типа на опережение?..

2023-02-26 22:49 UTC, Terro216 commented on src/styles/global.scss
> +  justify-content: space-between;
интересно там внизу две карточки по разным сторонам экрана получаются

2023-02-26 22:50 UTC, Terro216 reviewed
Хорошее начало.. жду продолжения

2023-02-26 22:51 UTC, Terro216 requested changes
Хорошее начало.. жду продолжения

2023-02-26 23:57 UTC, vyragosa commented
[https://youtu.be/S0bobui_gKk](🔪)

2023-02-26 23:57 UTC, vyragosa commented
[🔪](https://youtu.be/S0bobui_gKk)

2023-02-27 08:48 UTC, VasilyRazdorsky commented on src/styles/card.scss
> +  &__info {
Пока что думаю как реализовать его, из вёрстки убрал на время

2023-02-27 08:49 UTC, VasilyRazdorsky commented on src/styles/global.scss
> +  justify-content: space-between;
Переделаю гридом

2023-02-27 09:21 UTC, VasilyRazdorsky commented on src/pages/Home.tsx
>      queryKey: ['top'],
Нет смысла тк в дальнейшем не обязательно что я буду получать именно этот тип

2023-02-27 11:11 UTC, VasilyRazdorsky commented
Loader пока что не нашёл

2023-02-27 16:37 UTC, Terro216 commented on src/pages/Home.tsx
>      queryKey: ['top'],
поэтому потом будет динамический  { type: currentType }

2023-02-27 16:41 UTC, Terro216 commented on src/components/Card.tsx
> +        <p className='card__year'>Год: {year === undefined ? 'неизвестно' : year}</p>
```{ year || 'Неизвестно' }```

2023-02-27 16:42 UTC, Terro216 commented on src/styles/card.scss
> +      color: #e61919;
а где переменная для цвета

2023-02-27 16:46 UTC, VasilyRazdorsky commented on src/styles/card.scss
> +      color: #e61919;
Я больше этот цвет на планирую использовать, смысл его переменной делать

2023-02-27 16:50 UTC, VasilyRazdorsky commented on src/components/Card.tsx
> +        <p className='card__year'>Год: {year === undefined ? 'неизвестно' : year}</p>
Крутое решение!!!

2023-02-28 20:45 UTC, Terro216 commented on src/components/Card.tsx
> +        <p className='card__year'>Год: {year === undefined ? 'неизвестно' : year}</p>
не забыть 
```js
{year && <p className='card__year'>Год: {year}</p>}
```

2023-03-02 15:16 UTC, Terro216 commented on src/components/PageNavigation.tsx
> +      <NavLink
А зачем здесь `NavLink`? Он же обычно для навигации в меню используется
А тут наверное просто `Link` хватит

2023-03-02 15:24 UTC, Terro216 commented on src/pages/TopList.tsx
> +        {pagesCount ? <PageNavigation pagesCount={pagesCount} page={pageInt} type={type} /> : <p>Error</p>}
в пропс написать `={type === 'TOP_100_POPULAR_FILMS' ? 20 : filmsData.pagesCount}`
или поменять 21 строчку на `pagesCount = () => type === 'TOP_100_POPULAR_FILMS' ? 20 : filmsData.pagesCount` мб

2023-03-02 15:27 UTC, Terro216 reviewed
давай все комменты в этой ветке закроем/дообсудим

2023-03-02 17:57 UTC, Terro216 commented on src/components/PageNavigation.tsx
> +  const handleArrowClick = (direction: boolean) => {
что за булевое направление?)))
Сделай тип `"left"|"right"`

2023-03-02 17:57 UTC, Terro216 commented on src/components/PageNavigation.tsx
> +  const handleArrowClick = (direction: boolean) => {
или лучше `"back"|"forward"`

2023-03-02 17:58 UTC, Terro216 commented on src/pages/TopList.tsx
> +          {filmsData?.films.map((filmInfo) => (
тут можно убрать `?.` если ты уже вышел проверил существование `filmsData `

2023-03-02 19:27 UTC, VasilyRazdorsky commented on src/components/PageNavigation.tsx
> +  const handleArrowClick = (direction: boolean) => {
Ахахаха это было на скорую руку

2023-03-02 20:27 UTC, Terro216 commented on src/components/PageNavigation.tsx
> +  const handleArrowClick = (direction: string) => {
нее, давай уж `direction: "back" | "forward"`

2023-03-02 20:28 UTC, Terro216 approved these changes
исправь тип direction и сливай 👍🏻

2023-03-02 20:33 UTC, merged